Feature lista
valva-ro/TP5-Trialgo pull request #9
Opened 2020-07-28 17:26 UTC by alejovillores

2020-07-28 17:53 UTC, valva-ro requested changes
Ale hay una clase `Nodo.h` que es prácitamente igual a `Nodo_Lista.h`. Si podés borrar ésta y usar la que ya está subida en la rama `develop` mejor, me parece al pedo tenerlo duplicado. Las diferencias son los nombres de los métodos, pero hacen lo mismo.

Te dejo acá el [link](https://github.com/valva-ro/TP5-Trialgo/blob/develop/Nodo.h) de la clase Nodo.h

PD: Con _usarla_ me refiero a que incluyas en `Lista.h` a `Nodo.h` (en vez de `Nodo_Lista.h`), y que cambies los nombres de los métodos por los que están en esa clase `Nodo`. Cuando se mergee todo debería funcionar

2020-07-30 14:44 UTC, valva-ro requested changes
- En todos los templates dice `template<typedef Dato>`, hay que modificarlos por `template<typename Dato>` o `template<class Dato>`. El `typedef` se usa para asignarle otro nombre a un tipo de dato existente, es más específico que los templates
- Los métodos `getDato()`, `delDato()`, y `getTam()` están mal definidos, en vez de `void Lista:: delDato()` tiene que ser `void Lista<Dato>:: delDato()`

2020-07-30 14:44 UTC, valva-ro commented on Lista.h
>      while (!(this->lista_vacia()))
```suggestion
    while (!(this->listaVacia()))
```

2020-07-30 14:44 UTC, valva-ro commented on Lista.h
>  Dato Lista::getDato(unsigned pos)
```suggestion
Dato Lista<Dato>::getDato(unsigned pos)
```

2020-07-30 14:44 UTC, valva-ro commented on Lista.h
>  void Lista::delDato(unsigned pos)
```suggestion
void Lista<Dato>::delDato(unsigned pos)
```

2020-07-30 14:55 UTC, alejovillores commented
Oki

2020-07-30 17:55 UTC, valva-ro approved these changes

2020-07-31 13:24 UTC, valva-ro commented
Ale, podrás agregar un metodo que sea obtenerPosicion(Tipo dato)? Que recorra toda la lista hasta encontrar el dato recibido, y devuelva la posición en la que esta.
Porque en el grafo para acceder a una posicion de la matriz siempre vamos a necesitar chequear en que posición de la lista esta el dato, y me parece más fácil teniendo directamente un metodo en esta clase.

2020-07-31 22:40 UTC, alejovillores commented
Dale dale , mañana lo hago

2020-07-31 23:15 UTC, AlexTeper99 approved these changes
aproba3

2020-08-01 00:34 UTC, closed without merging